# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d391b462116315fb1b18eb23e3b66e6b0d489008e2c364bf3b13703bc09b5e879a3286d9143d7c56dfd19ea96999dc5f3658839afb411102bb76fa869880189

test:
  secret_key_base: df4ea1c171afd276056e7c184c253296ac85391de2527ec3989122d28100a24aa5970093b6cf5b761ab46bd504870e35f58c2591bc246f41507c71224998f1cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
